/** Default values for create-property form (matches API schema) */
export const EMPTY_HOTEL_FORM = {
  name: '',
  subdomain: '',
  slug: '',
  seo_keywords: '',
  property_type: 'hotel',
  country: '',
  city: '',
  address: '',
  phone: '',
  email: '',
  website: '',
  stars: 5,
  description: '',
  short_description: '',
  name_ar: '',
  description_ar: '',
  short_description_ar: '',
  is_active: false,
  latitude: '',
  longitude: '',
  amenity_ids: [],
  check_in_time: '',
  check_out_time: '',
  cancellation_policy: '',
  children_policy: '',
  pet_policy: '',
  smoking_policy: '',
  extra_bed_policy: '',
  cancellation_policy_ar: '',
  children_policy_ar: '',
  pet_policy_ar: '',
  smoking_policy_ar: '',
  extra_bed_policy_ar: '',
  facebook_url: '',
  instagram_url: '',
  tiktok_url: '',
  twitter_url: '',
  youtube_url: '',
  linkedin_url: '',
  video_url: '',
  booking_com_url: '',
  agoda_url: '',
  airbnb_url: '',
  expedia_url: '',
  primary_contact_person: '',
  contact_position: '',
  emergency_contact_number: '',
  cm_provider_name: '',
  cm_external_property_id: '',
  publishing_status: 'draft'
};

export const PROPERTY_TYPE_OPTIONS = [
  { value: 'hotel', label: 'Hotel' },
  { value: 'resort', label: 'Resort' },
  { value: 'apartment', label: 'Apartment' },
  { value: 'hostel', label: 'Hostel' },
  { value: 'villa', label: 'Villa' }
];

export const STAR_OPTIONS = [1, 2, 3, 4, 5];
